stages:
  data_ingestion:
    cmd: python src\EcoMeal\pipeline\data_ingestion.py
    deps:
      - src\EcoMeal\pipeline\data_ingestion.py
      - config\config.yaml
    outs:
      - artifacts\data_ingestion\Indian Food Images
    
  prepare_base_model:
    cmd: python src\EcoMeal\pipeline\prepare_base_model.py
    deps:
      - src\EcoMeal\pipeline\prepare_base_model.py
      - config\config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
      - LEARNING_RATE
    outs:
      - artifacts\prepare_base_model

  training:
    cmd: python src\EcoMeal\pipeline\model_training.py
    deps:
      - src\EcoMeal\pipeline\model_training.py
      - src\EcoMeal\components\prepare_callbacks.py
      - config\config.yaml
      - artifacts\data_ingestion\Indian Food Images
      - artifacts\prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGUMENTATION
    outs:
      - artifacts\model_training\model.keras

  evaluation:
    cmd: python src\EcoMeal\pipeline\model_evaluation.py
    deps:
      - src\EcoMeal\pipeline\model_evaluation.py
      - config\config.yaml
      - artifacts\data_ingestion\Indian Food Images
      - artifacts\model_training\model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false