artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://storage.googleapis.com/kaggle-data-sets/1243366/4077749/upload/Indian%20Food%20Images.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20241003%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20241003T123721Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=1ec62f1926438f053c2ad021fc77644994698e2a3b44a74e8f9f9d98a3112023dc2a025f4efbdd57bd515adc344089d32fa9b88a54970a64d2f48383bdf76fdbd93cbba212e847836ab0102377c2ad14e3e5290324ee311d1a86325ea61c201302b5274d375abd8453d49afa24105f1f66b754972806146244db7d61c0ccb6abb8f15ba80476b1ab98c5383c784a7d11db73e1bf18127d58a7c767c1aef87f18c6f8de81b27bec74ae507aa27e2895f7db36304aa28d7c7359e3a734f34e57f2315cb97e9637899e1b99a0db5d66f3f62f0b1f6f7c74b69b52785cc777ed73dbc047cc969d61baebaf881bd52ad17655a065ccb388249a892845895d6f4db3de
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.keras

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras

model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/model.keras